# Generated by Django 5.2.4 on 2025-07-14 14:19

import django.db.models.deletion
import tickets.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name="ticket",
            name="reserved_until",
            field=models.DateTimeField(
                blank=True,
                default=tickets.core.models.default_reserved_until,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="seat_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("reserved", "Reserved"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("used", "Used"),
                ],
                default="reserved",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="trip_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
