# Generated by Django 5.2.4 on 2025-07-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_tripinfocache"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tripinfocache",
            table="trip_info_cache",
        ),
    ]
