# Generated by Django 5.2.3 on 2025-08-22 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_ticket_pdf_file_ticket_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TripInfoCache",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="description",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="title",
        ),
        migrations.AddField(
            model_name="ticket",
            name="destination",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="invoice_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="origin",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
