# Generated by Django 5.2.3 on 2025-08-22 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_delete_tripinfocache_remove_ticket_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="destination",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="origin",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
