# Generated by Django 5.2.3 on 2025-09-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_ticket_destination_alter_ticket_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="refund_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
