# Generated by Django 5.2.3 on 2025-09-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_ticket_refund_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="can_cancel",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.ExpressionWrapper(
                    models.Q(("status__in", ["reserved", "paid"])),
                    output_field=models.BooleanField(),
                ),
                output_field=models.BooleanField(),
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="can_confirm",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.ExpressionWrapper(
                    models.Q(("status__in", ["reserved"])),
                    output_field=models.BooleanField(),
                ),
                output_field=models.BooleanField(),
            ),
        ),
    ]
