# Generated by Django 5.2.4 on 2025-07-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_ticket_price_ticket_reserved_until_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="pdf_file",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
