# Generated by Django 5.2.4 on 2025-07-21 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_ticket_pdf_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
            },
        ),
        migrations.AlterField(
            model_name="ticket",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat_number",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="trip_id",
            field=models.IntegerField(null=True),
        ),
    ]
