# Generated by Django 5.2.4 on 2025-07-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_ticket_options_alter_ticket_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripInfoCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_id", models.IntegerField(unique=True)),
                ("route_name", models.CharField(max_length=255)),
                ("bus_model", models.CharField(max_length=255)),
                ("bus_plate_number", models.CharField(max_length=50)),
                ("bus_capacity", models.PositiveSmallIntegerField()),
                ("driver_name", models.CharField(max_length=255)),
                ("driver_phone", models.CharField(max_length=20)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("from_city", models.CharField(max_length=100)),
                ("to_city", models.CharField(max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
