# Generated by Django 5.2.4 on 2025-07-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_tripinfocache_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tripinfocache",
            table="core_trip_info_cache",
        ),
    ]
