# Generated by Django 5.2.4 on 2025-07-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_tripinfocache_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripinfocache",
            name="trip_nr",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
