# Generated by Django 5.2.4 on 2025-07-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_tripinfocache_trip_nr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripinfocache",
            name="trip_nr",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
