# Generated by Django 5.2.3 on 2025-07-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_tripinfocache_trip_nr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="pdf_file",
        ),
        migrations.AddField(
            model_name="ticket",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="tickets/"),
        ),
    ]
